convert ._grande.png -resize 200x ../php/imagens/..png
convert brasilia_grande.png -resize 200x ../php/imagens/brasilia.png
convert Carro_Victoria10_grande.png -resize 200x ../php/imagens/Carro_Victoria10.png
convert carrinho_amarelo_grande.png -resize 200x ../php/imagens/carrinho_amarelo.png
convert carrinho_vermelho4_grande.png -resize 200x ../php/imagens/carrinho_vermelho4.png
convert esportivo_grande.png -resize 200x ../php/imagens/esportivo.png
convert carrinho_vermelho3_grande.png -resize 200x ../php/imagens/carrinho_vermelho3.png
convert executa_reduz_tamanho_img.bash_grande.png -resize 200x ../php/imagens/executa_reduz_tamanho_img.bash.png
convert carrinho_amarelo1_grande.png -resize 200x ../php/imagens/carrinho_amarelo1.png
convert Carro_Victoria_grande.png -resize 200x ../php/imagens/Carro_Victoria.png
convert executa_muda_nome_grande.bash_grande.png -resize 200x ../php/imagens/executa_muda_nome_grande.bash.png
convert carrinho_amarelo4_grande.png -resize 200x ../php/imagens/carrinho_amarelo4.png
convert brasilia_pequeno.png_grande.png -resize 200x ../php/imagens/brasilia_pequeno.png.png
convert carrinho_amarelo2_grande.png -resize 200x ../php/imagens/carrinho_amarelo2.png
convert carrinho_vermelho2_grande.png -resize 200x ../php/imagens/carrinho_vermelho2.png
convert fogo3_grande.png -resize 200x ../php/imagens/fogo3.png
convert carrinho_grande.png -resize 200x ../php/imagens/carrinho.png
convert parede_pequena_grande.png -resize 200x ../php/imagens/parede_pequena.png
convert carrinho_amarelo3_grande.png -resize 200x ../php/imagens/carrinho_amarelo3.png
convert \_grande.png -resize 200x ../php/imagens/\.png
convert fogo_grande.png -resize 200x ../php/imagens/fogo.png
convert gera_muda_nome_grande.bash_grande.png -resize 200x ../php/imagens/gera_muda_nome_grande.bash.png
convert gera_reduz_tamanho_img.bash_grande.png -resize 200x ../php/imagens/gera_reduz_tamanho_img.bash.png
convert teste_fantasia_grande.png -resize 200x ../php/imagens/teste_fantasia.png
convert teste_fundo_png_grande.png -resize 200x ../php/imagens/teste_fundo_png.png
convert carrinho_azul_grande.png -resize 200x ../php/imagens/carrinho_azul.png
convert family_car_grande.png -resize 200x ../php/imagens/family_car.png
convert carrinho_vermelho1_grande.png -resize 200x ../php/imagens/carrinho_vermelho1.png
convert carrinho2_grande.png -resize 200x ../php/imagens/carrinho2.png
convert fogo_victor_grande.png -resize 200x ../php/imagens/fogo_victor.png
convert fusca_grande.png -resize 200x ../php/imagens/fusca.png
convert fogo4_grande.png -resize 200x ../php/imagens/fogo4.png
convert fogo5_grande.png -resize 200x ../php/imagens/fogo5.png
convert fogo2_grande.png -resize 200x ../php/imagens/fogo2.png
convert carrinho_vermelho_grande.png -resize 200x ../php/imagens/carrinho_vermelho.png
