mv . _grande.png
mv brasilia.png brasilia_grande.png
mv carrinho_amarelo3.png carrinho_amarelo3_grande.png
mv carrinho_amarelo1.png carrinho_amarelo1_grande.png
mv fogo3.jpg fogo3_grande.png
mv carrinho_vermelho4.png carrinho_vermelho4_grande.png
mv parede_pequena.jpeg parede_pequena_grande.png
mv teste_fantasia.html teste_fantasia_grande.png
mv fogo5.png fogo5_grande.png
mv Carro_Victoria10.png Carro_Victoria10_grande.png
mv Carro_Victoria.png Carro_Victoria_grande.png
mv carrinho_vermelho1.png carrinho_vermelho1_grande.png
mv family_car.png family_car_grande.png
mv teste_fundo_png.html teste_fundo_png_grande.png
mv carrinho_azul.png carrinho_azul_grande.png
mv fogo.png fogo_grande.png
mv carrinho_vermelho2.png carrinho_vermelho2_grande.png
mv esportivo.png esportivo_grande.png
mv carrinho_vermelho.png carrinho_vermelho_grande.png
mv fogo4.png fogo4_grande.png
mv executa_muda_nome.bash executa_muda_nome_grande.png
mv carrinho.png carrinho_grande.png
mv carrinho_amarelo4.png carrinho_amarelo4_grande.png
mv carrinho_vermelho3.png carrinho_vermelho3_grande.png
mv carrinho_amarelo2.png carrinho_amarelo2_grande.png
mv carrinho2.png carrinho2_grande.png
mv fogo_victor.png fogo_victor_grande.png
mv fogo2.png fogo2_grande.png
mv fusca.png fusca_grande.png
mv carrinho_amarelo.png carrinho_amarelo_grande.png
